# Generated by Django 4.0 on 2024-04-27 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SzkołaAIDjango_web', '0002_article_year_alter_article_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='contetnt',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
