# Generated by Django 4.0 on 2024-04-27 11:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SzkołaAIDjango_web', '0003_article_contetnt_article_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='contetnt',
            new_name='content',
        ),
        migrations.AddField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
